version: '3.8'

services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    environment:
      - DJANGO_ALLOWED_HOSTS=127.0.0.1,localhost
    volumes:
      - ./task_manager:/app
    ports:
      - "8000:8000"
