# Generated by Django 4.2.3 on 2024-07-15 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='name',
            field=models.CharField(blank=True, default='New Project', max_length=50),
        ),
    ]
